apiVersion: v1
kind: Namespace
metadata:
  name: mwb-deploy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-agent
  namespace: mwb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deploy-agent
  template:
    metadata:
      labels:
        app: deploy-agent
    spec:
      containers:
        - name: deploy-agent
          image: mwb-deploy-agent:latest
          ports:
            - containerPort: 9090
          env:
            - name: KUBECONFIG
              value: /etc/kube/config
---
apiVersion: v1
kind: Service
metadata:
  name: deploy-agent
  namespace: mwb-deploy
spec:
  selector:
    app: deploy-agent
  ports:
    - port: 9090
      targetPort: 9090
