#!/usr/bin/env bash
# Provision VPS for package catalog (Next.js + Postgres + PM2). No Docker.
# Idempotent where practical. Does NOT overwrite existing web/.env unless FORCE_ENV=1.
#
# Usage:
#   cp .deploy.env.example .deploy.env
#   make setup-server
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

die() { echo "error: $*" >&2; exit 1; }
need() { command -v "$1" >/dev/null 2>&1 || die "missing required command: $1"; }
log() { echo "==> $*"; }

load_env_file() {
  local f="$1"
  [[ -f "$f" ]] || return 0
  local line key val
  while IFS= read -r line || [[ -n "$line" ]]; do
    line="${line%$'\r'}"
    [[ -z "$line" || "$line" =~ ^[[:space:]]*# ]] && continue
    key="${line%%=*}"
    val="${line#*=}"
    key="$(echo "$key" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
    case "$val" in
      \"*\") val="${val#\"}"; val="${val%\"}" ;;
      \'*\') val="${val#\'}"; val="${val%\'}" ;;
    esac
    if [[ -z "${!key+x}" ]]; then
      export "$key=$val"
    fi
  done < "$f"
}

load_env_file "$ROOT/.deploy.env"

need ssh
need sshpass
need openssl

SERVER_IP="${SERVER_IP:-}"
SERVER_USER="${SERVER_USER:-root}"
SERVER_PASSWORD="${SERVER_PASSWORD:-${SSHPASS:-}}"
DOMAIN="${DOMAIN:-app.vyaparnext.com}"
APP_NAME="${APP_NAME:-medusa-web-builder}"
SITE_URL="${SITE_URL:-https://${DOMAIN}}"
WEB_PORT="${WEB_PORT:-8020}"
DEPLOY_ROOT="${DEPLOY_ROOT:-~/deploy/${APP_NAME}}"
SSL_DIR="${SSL_DIR:-/etc/ssl/smartbytelabs}"
SSL_BASENAME="${SSL_BASENAME:-app-vyaparnext}"
DB_NAME="${DB_NAME:-medusa_web_builder}"
DB_USER="${DB_USER:-mwb}"
DB_PASSWORD="${DB_PASSWORD:-}"
NODE_VERSION="${NODE_VERSION:-22}"
FORCE_DB="${FORCE_DB:-0}"
FORCE_ENV="${FORCE_ENV:-0}"
SKIP_SSL="${SKIP_SSL:-0}"
SKIP_NGINX="${SKIP_NGINX:-0}"
SKIP_NODE="${SKIP_NODE:-0}"
SKIP_DB="${SKIP_DB:-0}"

[[ -n "$SERVER_IP" ]] || die "SERVER_IP is required"
[[ -n "$SERVER_PASSWORD" ]] || die "SERVER_PASSWORD (or SSHPASS) is required"
[[ -n "$DOMAIN" ]] || die "DOMAIN is required"
[[ "$APP_NAME" =~ ^[a-z0-9][a-z0-9_-]*$ ]] || die "APP_NAME must be lowercase alphanumeric/_-"
[[ "$DB_NAME" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] || die "DB_NAME must be a valid PostgreSQL identifier"
[[ "$DB_USER" =~ ^[a-zA-Z_][a-zA-Z0-9_]*$ ]] || die "DB_USER must be a valid PostgreSQL identifier"

[[ -n "$DB_PASSWORD" ]] || DB_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
AUTH_SECRET="${AUTH_SECRET:-$(openssl rand -base64 32 | tr -d '/+=' | head -c 48)}"
ENCRYPTION_KEY="${ENCRYPTION_KEY:-$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)}"

upsert_env() {
  local f="$1" k="$2" v="$3"
  touch "$f"
  if grep -q "^${k}=" "$f" 2>/dev/null; then
    if sed --version >/dev/null 2>&1; then
      sed -i "s|^${k}=.*|${k}=${v}|" "$f"
    else
      sed -i '' "s|^${k}=.*|${k}=${v}|" "$f"
    fi
  else
    printf '%s=%s\n' "$k" "$v" >> "$f"
  fi
}

persist_local_deploy_env() {
  local f="$ROOT/.deploy.env"
  upsert_env "$f" SERVER_IP "$SERVER_IP"
  upsert_env "$f" SERVER_USER "$SERVER_USER"
  upsert_env "$f" SERVER_PASSWORD "$SERVER_PASSWORD"
  upsert_env "$f" DOMAIN "$DOMAIN"
  upsert_env "$f" APP_NAME "$APP_NAME"
  upsert_env "$f" SITE_URL "$SITE_URL"
  upsert_env "$f" WEB_PORT "$WEB_PORT"
  upsert_env "$f" DEPLOY_ROOT "$DEPLOY_ROOT"
  upsert_env "$f" REMOTE_WEB_DIR "${DEPLOY_ROOT}/web"
  upsert_env "$f" WEB_PM2_NAME "${APP_NAME}-web"
  upsert_env "$f" DB_NAME "$DB_NAME"
  upsert_env "$f" DB_USER "$DB_USER"
  upsert_env "$f" DB_PASSWORD "$DB_PASSWORD"
  upsert_env "$f" SSL_DIR "$SSL_DIR"
  upsert_env "$f" SSL_BASENAME "$SSL_BASENAME"
  upsert_env "$f" AUTH_SECRET "$AUTH_SECRET"
  upsert_env "$f" ENCRYPTION_KEY "$ENCRYPTION_KEY"
}

export SSHPASS="$SERVER_PASSWORD"
SSH_BASE=(sshpass -e ssh
  -o StrictHostKeyChecking=no
  -o PreferredAuthentications=password
  -o PubkeyAuthentication=no
  -o ConnectTimeout=30
)
SCP_BASE=(sshpass -e scp
  -o StrictHostKeyChecking=no
  -o PreferredAuthentications=password
  -o PubkeyAuthentication=no
  -o ConnectTimeout=30
)
REMOTE="${SERVER_USER}@${SERVER_IP}"

WORKDIR="$(mktemp -d "${TMPDIR:-/tmp}/mwb-setup.XXXXXX")"
cleanup() { rm -rf "$WORKDIR"; }
trap cleanup EXIT

log "Provisioning ${APP_NAME} on ${REMOTE} for ${DOMAIN} (PM2, no Docker)"
persist_local_deploy_env

UPSTREAM_NAME="${APP_NAME//-/_}_web"

cat > "$WORKDIR/${DOMAIN}.nginx" <<NGINX
# ${APP_NAME} — generated by scripts/setup-server.sh
upstream ${UPSTREAM_NAME} {
    server 127.0.0.1:${WEB_PORT};
    keepalive 32;
}

server {
    listen 80;
    listen [::]:80;
    server_name ${DOMAIN};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ${DOMAIN};

    ssl_certificate     ${SSL_DIR}/${SSL_BASENAME}.crt;
    ssl_certificate_key ${SSL_DIR}/${SSL_BASENAME}.key;
    ssl_protocols       TLSv1.2 TLSv1.3;

    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;

    client_max_body_size 120m;

    access_log /var/log/nginx/${APP_NAME}.access.log;
    error_log  /var/log/nginx/${APP_NAME}.error.log;

    location / {
        proxy_pass http://${UPSTREAM_NAME};
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 120s;
        proxy_send_timeout 120s;
    }
}
NGINX

cat > "$WORKDIR/ecosystem.config.cjs" <<ECO
module.exports = {
  apps: [
    {
      name: "${APP_NAME}-web",
      cwd: "__WEB_DIR__",
      script: "apps/web/server.js",
      instances: 1,
      exec_mode: "fork",
      env: {
        NODE_ENV: "production",
        PORT: "${WEB_PORT}",
        HOSTNAME: "0.0.0.0",
      },
      out_file: "__LOG_DIR__/web.out.log",
      error_file: "__LOG_DIR__/web.err.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      max_memory_restart: "512M",
      time: true,
    },
  ],
};
ECO

cat > "$WORKDIR/web.env" <<ENVW
NODE_ENV=production
PORT=${WEB_PORT}
HOSTNAME=0.0.0.0
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@127.0.0.1:5432/${DB_NAME}?schema=public
NEXTAUTH_URL=${SITE_URL}
AUTH_SECRET=${AUTH_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}
CATALOG_S3_BUCKET=${CATALOG_S3_BUCKET:-}
CATALOG_S3_REGION=${CATALOG_S3_REGION:-ap-south-1}
CATALOG_S3_ACCESS_KEY_ID=${CATALOG_S3_ACCESS_KEY_ID:-}
CATALOG_S3_SECRET_ACCESS_KEY=${CATALOG_S3_SECRET_ACCESS_KEY:-}
CATALOG_S3_PUBLIC_URL=${CATALOG_S3_PUBLIC_URL:-}
ENVW

cat > "$WORKDIR/remote-setup.sh" <<'REMOTE'
#!/usr/bin/env bash
set -euo pipefail

APP_NAME="$1"
DOMAIN="$2"
WEB_PORT="$3"
DEPLOY_ROOT_RAW="$4"
SSL_DIR="$5"
SSL_BASENAME="$6"
DB_NAME="$7"
DB_USER="$8"
DB_PASSWORD="$9"
FORCE_DB="${10}"
NODE_VERSION="${11}"
SKIP_SSL="${12}"
SKIP_NGINX="${13}"
SKIP_NODE="${14}"
SKIP_DB="${15}"
FORCE_ENV="${16}"

DEPLOY_ROOT=$(eval echo "$DEPLOY_ROOT_RAW")
WEB_DIR="$DEPLOY_ROOT/web"
LOG_DIR="$DEPLOY_ROOT/logs"
STAGE="/tmp/${APP_NAME}-setup-files"

echo "==> Deploy root: $DEPLOY_ROOT"
mkdir -p "$WEB_DIR" "$LOG_DIR" "$SSL_DIR"

export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y curl ca-certificates gnupg build-essential openssl nginx rsync

# Stop leftover Docker catalog stack if present (we no longer use Docker for this app)
if command -v docker >/dev/null 2>&1; then
  if [[ -f "$DEPLOY_ROOT/docker/docker-compose.prod.yml" ]]; then
    (cd "$DEPLOY_ROOT" && docker compose -f docker/docker-compose.prod.yml --env-file .env down 2>/dev/null) || true
  fi
fi

if [[ "$SKIP_DB" != "1" ]]; then
  echo "==> Postgres"
  if ! command -v psql >/dev/null 2>&1; then
    apt-get install -y postgresql postgresql-contrib
    systemctl enable --now postgresql
  fi
  if sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" | grep -q 1; then
    echo "Role ${DB_USER} exists"
    if [[ "$FORCE_DB" == "1" ]]; then
      sudo -u postgres psql -c "ALTER USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';"
    fi
  else
    sudo -u postgres psql -c "CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASSWORD}';"
  fi
  if sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1; then
    echo "Database ${DB_NAME} exists"
  else
    sudo -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};"
  fi
  sudo -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DB_NAME} TO ${DB_USER};"
  sudo -u postgres psql -d "${DB_NAME}" -c "GRANT ALL ON SCHEMA public TO ${DB_USER};" || true
  sudo -u postgres psql -d "${DB_NAME}" -c "ALTER SCHEMA public OWNER TO ${DB_USER};" || true
fi

if [[ "$SKIP_NODE" != "1" ]]; then
  echo "==> Node ${NODE_VERSION} + pm2"
  if [[ ! -s "$HOME/.nvm/nvm.sh" ]]; then
    curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash
  fi
  # shellcheck disable=SC1091
  . "$HOME/.nvm/nvm.sh"
  nvm install "$NODE_VERSION"
  nvm alias default "$NODE_VERSION"
  npm install -g pm2@latest
  pm2 startup systemd -u root --hp /root >/dev/null 2>&1 || true
fi

if [[ "$SKIP_SSL" != "1" ]]; then
  CRT="${SSL_DIR}/${SSL_BASENAME}.crt"
  KEY="${SSL_DIR}/${SSL_BASENAME}.key"
  if [[ -f "$CRT" && -f "$KEY" ]]; then
    echo "SSL cert exists: $CRT"
  else
    echo "==> Self-signed SSL for ${DOMAIN}"
    openssl req -x509 -nodes -days 825 -newkey rsa:2048 \
      -keyout "$KEY" -out "$CRT" \
      -subj "/CN=${DOMAIN}/O=Smart Byte Labs/C=IN" \
      -addext "subjectAltName=DNS:${DOMAIN}"
    chmod 600 "$KEY"
    chmod 644 "$CRT"
  fi
fi

if [[ "$SKIP_NGINX" != "1" ]]; then
  echo "==> Nginx site ${DOMAIN}"
  cp "$STAGE/${DOMAIN}.nginx" "/etc/nginx/sites-available/${DOMAIN}"
  ln -sfn "/etc/nginx/sites-available/${DOMAIN}" "/etc/nginx/sites-enabled/${DOMAIN}"
  nginx -t
  systemctl enable --now nginx
  systemctl reload nginx
fi

sed -e "s|__WEB_DIR__|${WEB_DIR}|g" -e "s|__LOG_DIR__|${LOG_DIR}|g" \
  "$STAGE/ecosystem.config.cjs" > "$DEPLOY_ROOT/ecosystem.config.cjs"

if [[ -f "$WEB_DIR/.env" && "$FORCE_ENV" != "1" ]]; then
  echo "Keeping existing $WEB_DIR/.env (FORCE_ENV=1 to overwrite)"
else
  cp "$STAGE/web.env" "$WEB_DIR/.env"
  chmod 600 "$WEB_DIR/.env"
  echo "Wrote $WEB_DIR/.env"
fi

echo ""
echo "Setup complete for ${DOMAIN}"
echo "  Deploy root: $DEPLOY_ROOT"
echo "  Web port:    $WEB_PORT"
echo "  Next:        make deploy-local"
echo "  Cloudflare:  A ${DOMAIN} → this server IP, SSL/TLS mode Full"
REMOTE

mkdir -p "$WORKDIR/stage"
cp "$WORKDIR/${DOMAIN}.nginx" "$WORKDIR/stage/"
cp "$WORKDIR/ecosystem.config.cjs" "$WORKDIR/stage/"
cp "$WORKDIR/web.env" "$WORKDIR/stage/"
cp "$WORKDIR/remote-setup.sh" "$WORKDIR/stage/"
chmod +x "$WORKDIR/stage/remote-setup.sh"

log "Uploading setup files"
"${SSH_BASE[@]}" "$REMOTE" "rm -rf /tmp/${APP_NAME}-setup-files && mkdir -p /tmp/${APP_NAME}-setup-files"
"${SCP_BASE[@]}" -r "$WORKDIR/stage/." "$REMOTE:/tmp/${APP_NAME}-setup-files/"

log "Running remote setup"
"${SSH_BASE[@]}" "$REMOTE" \
  "bash /tmp/${APP_NAME}-setup-files/remote-setup.sh \
    '${APP_NAME}' '${DOMAIN}' '${WEB_PORT}' '${DEPLOY_ROOT}' \
    '${SSL_DIR}' '${SSL_BASENAME}' '${DB_NAME}' '${DB_USER}' '${DB_PASSWORD}' \
    '${FORCE_DB}' '${NODE_VERSION}' '${SKIP_SSL}' '${SKIP_NGINX}' '${SKIP_NODE}' \
    '${SKIP_DB}' '${FORCE_ENV}'"

log "Done. Point Cloudflare DNS at ${SERVER_IP}, then: make deploy-local"
